#!/usr/bin/env bash
# Assembles vendor/zenoh-pico into an Arduino 1.5-format library folder for
# the ESP32 sensor/Ethernet bridge firmware. Mirrors the source list
# that vendor/zenoh-pico/CMakeLists.txt + cmake/platforms/arduino_esp32.cmake
# would compile, since that CMake config is native-only (no ESP32 toolchain)
# and only used here to generate config.h.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=vendor/zenoh-pico
CFG_BUILD=build/zenoh-arduino-config
OUT=firmware/esp32_bridge/lib/zenoh-pico

rm -rf "$OUT"
mkdir -p "$OUT/src"

# 1. Headers (include/ becomes src/ root so `#include <zenoh-pico.h>` and
#    `#include "zenoh-pico/..."` both resolve under Arduino's library search).
cp -r "$SRC/include/." "$OUT/src/"

# 2. Generated config.h (arduino_esp32 platform, produced by
#    `cmake -S vendor/zenoh-pico -B build/zenoh-arduino-config -DZP_PLATFORM=arduino_esp32`)
#    overwrites the unexpanded config.h.in copy from step 1.
if [ ! -f "$CFG_BUILD/include/zenoh-pico/config.h" ]; then
    echo "Missing $CFG_BUILD/include/zenoh-pico/config.h — run cmake configure first:" >&2
    echo "  cmake -S $SRC -B $CFG_BUILD -DZP_PLATFORM=arduino_esp32 -DZ_FEATURE_LINK_UDP_MULTICAST=1" >&2
    exit 1
fi
cp "$CFG_BUILD/include/zenoh-pico/config.h" "$OUT/src/zenoh-pico/config.h"

# 3. Core sources (mirrors CMakeLists.txt `Sources` GLOB_RECURSE list).
for d in api collections net protocol runtime session transport utils; do
    mkdir -p "$OUT/src/$d"
    cp -r "$SRC/src/$d/." "$OUT/src/$d/"
done
mkdir -p "$OUT/src/system/common"
cp -r "$SRC/src/system/common/." "$OUT/src/system/common/"

# 4. Link sources (mirrors CMakeLists.txt `LinkSources` GLOB + explicit list).
mkdir -p "$OUT/src/link/config" "$OUT/src/link/multicast" "$OUT/src/link/unicast" \
         "$OUT/src/link/transport/common" "$OUT/src/link/transport/tcp" "$OUT/src/link/transport/udp" \
         "$OUT/src/link/transport/upper"
cp -r "$SRC/src/link/config/." "$OUT/src/link/config/"
cp -r "$SRC/src/link/multicast/." "$OUT/src/link/multicast/"
cp -r "$SRC/src/link/unicast/." "$OUT/src/link/unicast/"
cp -r "$SRC/src/link/transport/common/." "$OUT/src/link/transport/common/"
cp "$SRC/src/link/link.c" "$OUT/src/link/link.c"
cp "$SRC/src/link/endpoint.c" "$OUT/src/link/endpoint.c"
cp "$SRC/src/link/transport/tcp/address.c" "$OUT/src/link/transport/tcp/address.c"
cp "$SRC/src/link/transport/udp/address.c" "$OUT/src/link/transport/udp/address.c"
mkdir -p "$OUT/src/link/transport/serial"
cp "$SRC/src/link/transport/upper/serial_protocol.c" "$OUT/src/link/transport/upper/serial_protocol.c" 2>/dev/null || \
    mkdir -p "$OUT/src/link/transport/upper"
cp "$SRC/src/link/transport/upper/tls_stream.c" "$OUT/src/link/transport/upper/tls_stream.c"

# 5. Platform sources (cmake/platforms/arduino_esp32.cmake ZP_PLATFORM_SOURCE_FILES).
mkdir -p "$OUT/src/system/arduino/esp32" "$OUT/src/system/socket" \
         "$OUT/src/link/transport/bt" "$OUT/src/link/transport/serial"
cp "$SRC/src/system/arduino/esp32/system.c" "$OUT/src/system/arduino/esp32/system.c"
cp "$SRC/src/link/transport/bt/bt_arduino_esp32.cpp" "$OUT/src/link/transport/bt/bt_arduino_esp32.cpp"
cp "$SRC/src/system/socket/esp32.c" "$OUT/src/system/socket/esp32.c"
cp "$SRC/src/link/transport/tcp/tcp_esp32.c" "$OUT/src/link/transport/tcp/tcp_esp32.c"
cp "$SRC/src/link/transport/udp/udp_esp32.c" "$OUT/src/link/transport/udp/udp_esp32.c"
cp "$SRC/src/link/transport/udp/udp_multicast_esp32.c" "$OUT/src/link/transport/udp/udp_multicast_esp32.c"
cp "$SRC/src/link/transport/serial/uart_arduino_esp32.cpp" "$OUT/src/link/transport/serial/uart_arduino_esp32.cpp"

# 6. Drop raw-ethernet + unused transports that the ESP32 platform never
#    builds (kept out of vendor/ instead of relying on #if guards, since
#    esp32.h #errors out if Z_FEATURE_RAWETH_TRANSPORT ever gets set to 1).
rm -rf "$OUT/src/transport/raweth"
rm -f "$OUT/src/link/transport/serial/uart_espidf.c"

cat > "$OUT/library.properties" << 'EOF'
name=zenoh-pico-w5500
version=1.0.0
author=vendored from zenoh-pico (ZettaScale, EPL-2.0 OR Apache-2.0)
maintainer=hwkim3330
sentence=zenoh-pico assembled for ESP32 Arduino (arduino_esp32 platform) for this sensor/Ethernet bridge
paragraph=Generated by scripts/50-build-zenoh-arduino-lib.sh. Do not edit by hand; re-run the script after updating vendor/zenoh-pico.
category=Communication
url=https://github.com/eclipse-zenoh/zenoh-pico
architectures=esp32
EOF

echo "Wrote $OUT ($(find "$OUT/src" -name '*.c' -o -name '*.cpp' | wc -l) source files)"
